#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    TEST-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^test\.ddev\.site$`)
      
      service: "TEST-web-80"
      tls: false
      # middlewares:
      #   - "TEST-redirectHttps"
    TEST-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^test\.ddev\.site$`)
      
      service: "TEST-web-8025"
      tls: false
      # middlewares:
      #   - "TEST-redirectHttps"
    TEST-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^test\.ddev\.site$`)
      
      service: "TEST-xhgui-80"
      tls: false
      # middlewares:
      #   - "TEST-redirectHttps"
    
    
    
    TEST-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^test\.ddev\.site$`)
      
      service: "TEST-web-80"
      
      tls: true
      
    TEST-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^test\.ddev\.site$`)
      
      service: "TEST-web-8025"
      
      tls: true
      
    
    TEST-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^test\.ddev\.site$`)
      
      service: "TEST-xhgui-80"
      
      tls: true
      
    

  middlewares:
    TEST-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    TEST-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-TEST-web:80
        
    TEST-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-TEST-web:8025
        
    
    
    TEST-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-TEST-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/TEST.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/TEST.key